export const LANDING = '/'
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const SERVICE_PROVIDER_LIST = '/serviceproviders';
export const CALENDAR= '/calendar';
export const HOME_PAGE = '/home';
export const INSIDE_OUT ='/insideout';
export const DATA = '/data';
export const ABOUT = '/about';
export const MOVEMENT = '/movement';
export const DATA_ECONOMIC = '/data/economic';
export const DATA_INCARCERATION = '/data/incarceration';
export const DATA_DECARCERATION = '/data/decrceration';
export const MAP = '/map';
export const legislation = '/legislation';
export const ACCOUNT = '/myaccount';