module.exports = {
  myServices: [
    {
      Label: "Alma Center",
      Type: "Non-Profit",
      'Program and Services': [ "Men Ending Violence" ],
      Description: "\"Trauma and healing-informed program focusing on:\nTrauma resolution and education program that explores the \nroot causes of intimate partner violence. \nFocuses on healing past trauma and developing attitudes \nand behavior that will support respectful intimate partner \nrelationships in the future. \nDirectly works with men (partners, husbands, fathers) the \ngoal is to help their children.\nPrevent the men from transferring their pain to the next \ngeneration of children.\"",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "2821 N. Vel R. Phillips \nAve. 3rd Floor, \nMilwaukee, WI 53212",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 1,
      lat: 43,
      long: -88
    },         
    {
      Label: "Alma Center",
      Type: "Non-Profit",
      'Program and Services': [ "Restorative Fatherhood" ],
      Description: "Fatherhood education program helps men who have been abusive recognize, acknowledge and, when safe and possible, ameliorate the trauma they have caused their own children.\nFocuses on exploring personal experiences of fathering to learn compassion, forgiveness, responsibility, and to build positive, trauma - informed and developmentally appropriate nurturing fathering and co-parenting values, attitudes, and skills.",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "2821 N. Vel R. Phillips \nAve. 3rd Floor, \nMilwaukee, WI 53212",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 2,
      lat: 43.0385255,
      long: -87.908047
    },        
    {
      Label: "Alma Center",
      Type: "Non-Profit",
      'Program and Services': [ "Wisdom Walk to Self-Mastery" ],
      Description: "Therapeutic techniques with indigenous healing wisdom.\nParticipants progress through the healing circle as if they are on a journey through the five elemental landscapes (fire, water, earth, nature, mineral).\nExercises, activities and rituals focus on cognitive, affective and behavioral recovery/ restoration to transform the debility of trauma to strength that can help men assume their full responsibilities in their families and communities.",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "2821 N. Vel R. Phillips \nAve. 3rd Floor, \nMilwaukee, WI 53212",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 2,
      lat: 43.040446,
      long: -87.9151633
    },
    {
      Label: "Alma Center",
      Type: "Non-Profit",
      'Program and Services': [ "Reentry Services" ],
      Description: "Healing - focused services to individuals who are returning to the community from incarceration.\nAlma Brothers - an offender reentry project designed to address unresolved underlying trauma that predicts anti-social and criminal behavior and heightens the risk for ongoing criminal system involvement. \nSmart Reentry - an innovative reentry employment program for high-risk offenders returning from imprisonment to the Center Street Corridor, an area of Milwaukee plagued by gun violence.",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "2821 N. Vel R. Phillips \nAve. 3rd Floor, \nMilwaukee, WI 53212",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 3,
      lat: 43.040446,
      long: -87.9151633
    },
    {
      Label: "Wisconsin Community Services (WCS)",
      Type: "Non-Profit",
      'Program and Services': [ "Assertive Community Treatment (ACT)"],
      Description: "\"The Community Support Program (CSP) - provides coordinated care and a range of treatment, rehabilitation and support services for individuals living in the community with severe and persistent mental illness with possible challenges related to abusing alcohol and other drugs. CSP provides services utilizing the evidence-based practice, Assertive Community Treatment (ACT) and Tools for Measurement of Assertive Community treatment (TMACT). Using the ACT model, a multidisciplinary intensive team-based approach provides participants services that are long-term, but with the ability to transition. These services include stage-wise interventions based on the participant’s wants and needs, including individual and group therapy along with other interventions to promote health. These services include: \n• Advocacy\n• Assessment\n• Benefit assistance\n• Psychiatry\n• Nursing\n• Case management/care coordination\n• Supportive groups\n• Medication assistance\n• Money management\n• On-site Pharmacy\n• Social support network\n\nTo be eligible for participation in the Assertive Community Treatment program, a consumer must:\n\n• Be 18 or older\n• Have a severe mental illness such as schizophrenia, bi-polar disorder or major depression\n• Have experienced difficulties in the last six months with housing, employment, medication management, legal issues, money management, or a worsening of symptoms that required emergency intervention or hospitalization\"",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "3734 West Wisconsin Avenue\nMilwaukee, WI 53208",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 4,
      lat: 43.040446,
      long: -87.9151633
    },
    {
      Label: "Wisconsin Community Services (WCS)",
      Type: "Non-Profit",
      'Program and Services': [ "Community Case Management"],
      Description: "\"Targeted Case Management (TCM) \nThe Targeted Case Management Program (TCM) program assesses individual’s needs by working together with the individual to create a treatment plan. This assessment can include physical, psychological and social environment needs with the goal of facilitating personal health, community involvement, and empowerment while supporting the individual’s recovery. Some of the services provided through the TCM include:\n\n• Advocacy\n• Assessment\n• Benefit Assistance\n• Psychiatry\n• Individual Service Plan development\n• Care coordination\n• Crisis assistance planning\n• Medication Assistance\n• Money Management\n• On-site Pharmacy\n• Social Support Network\"",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "3732 West Wisconsin Avenue, Suite 310 \nMilwaukee, WI 53208 \n\nHours: 8:30am - 4:30pm Monday - Friday \n",
      Phone: "(414) 343-3569",
      Fax: "(414) 343-3598",
      Email: "",
      Website: "https://www.wiscs.org/programs/",
      Attributions: "",
      id: 5,
      lat: 43.040446,
      long: -87.9151633
    },
    {
      Label: "Wisconsin Community Services (WCS)",
      Type: "Non-Profit",
      'Program and Services': [ "WIser Choice Programming"],
      Description: "WCS is a provider of Wisconsin Supports Everyone´s Recovery Choice (WIser Choice) services. This programming provides individuals that need drug and alcohol treatment vouchers to pay for a range of appropriate community-based services. The Wiser Choice programming serves individuals that reside in Milwaukee County, are at least 18 years old, and do not have insurance. These strength-based services are person centered with a team approach that is outcome oriented. The WCS programs included in this area are Access Point (AP) and the Recovery Support Coordination Unit (RSC).\n\nAccess Point\nWCS operates an Access Point unit that will screen individuals to help determine the AODA needs as well as the options available to best meet these needs. This program gives individuals the opportunity to not only deal substance use concerns, but also access to many other supportive services. The WCS Access Point unit is mobile. The Access Point screener can see individuals at the WCS office, or we will travel to homes, correctional institutions, Department of Correction’s offices, and other locations that will meet the individual’s needs.\n\nRecovery Support Coordination (RSC)\nThe Recovery Support Coordination (RSC) Program provides Care Coordination services for adults with substance abuse and co-occurring mental health and substance abuse needs. With the support of a team, individuals create a Recovery Plan. We also provide Recovery Support Coordination services for a specialized group, Family Drug Treatment Court. Individuals interested in this program must be screened through Access Point, which can be done at the same location as our RSC program. Through the RSC program an individual will also have access to supportive services for employment, housing, transportation, medical treatment, and more." ,
      Tags: [ "Behavioral and Mental Health", "Employment", "Housing" ] ,
      Address: "3732 West Wisconsin Avenue, Suite 310 \nMilwaukee, WI 53208 \n\nHours: 8:30am - 4:30pm Monday - Friday \n" ,
      Phone: "(414) 343-3569" ,
      Fax: "(414) 343-3598" ,
      Email: "" ,
      Website: "https://www.wiscs.org/programs/" ,
      Attributions: "",
      id: 6,
      lat: 43.040446,
      long: -87.9151633
    },
    {
      Label: "Wisconsin Community Services (WCS)",
      Type: "Non-Profit",
      'Program and Services': [ "Joshua Glover Residential Reentry Center"],
      Description: "GOAL\nThe goal of the Joshua Glover Residential Reentry Center (RRC) is to effectively supervise and treat residents of the 36 male bed facility by addressing their identified criminogenic risks and needs. Ultimately, Joshua Glover RRC strives to reduce recidivism and to promote public safety through an array of therapeutic interventions.\n\nPROGRAM METHOD\nJoshua Glover RRC incorporates Evidence-Based Practices (EBP) into its service delivery to effectively address criminogenic risks and needs that were identified on the COMPASS for each resident. An individualized service plan is created with the input of the resident, Department of Corrections Probation Officer, AODA Counselor/Case Manager, and Mental Health Counselor, which is utilized by the staff to assist the resident with accomplishing his goals while at Joshua Glover RRC.\n\nPROGRAMS AND SERVICES\nResidents are assessed, referred to any identified services that are needed, and given support to successfully complete the program. The programs and services offered at the Joshua Glover RRC include:\n• Case management\n• Substance abuse individual/group counseling\n• Mental Health counseling\n• Cognitive Intervention group counseling\n• Employment Counseling\n• Fatherhood\n• Community Building Workshops\n\nVALUE ADDED SERVICES\nThe current value-added services include:\n• Mindfulness\n• Nutrition\n• Hero’s Journey\n• Beginner Computers\n• Dollars and Sense\n• Journaling\n\n",
      Tags: [ "Behavioral and Mental Health", "Employment" ],
      Address: "Joshua Glover Residential Reentry Center (Wisconsin DOC)\n2404 North 50th Street\nMilwaukee, WI 53210\n\n",
      Phone: "(414) 442-3700 \n",
      Fax: "(414) 442-6466",
      Email: "",
      Website: "https://www.wiscs.org/programs/",
      Attributions: "",
      id: 7,
      lat: 43.040446,
      long: -87.9151633
    },          
  ]
};
