module.exports = {
  myServices: [
    {
      Label: "Alma Center",
      Type: "Non-Profit",
      'Program and Services': [ "Men Ending Violence" ],
      Description: "\"Trauma and healing-informed program focusing on:\nTrauma resolution and education program that explores the \nroot causes of intimate partner violence. \nFocuses on healing past trauma and developing attitudes \nand behavior that will support respectful intimate partner \nrelationships in the future. \nDirectly works with men (partners, husbands, fathers) the \ngoal is to help their children.\nPrevent the men from transferring their pain to the next \ngeneration of children.\"",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "2821 N. Vel R. Phillips \nAve. 3rd Floor, \nMilwaukee, WI 53212",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 1,
      lat: 43.072177,
      long: -87.909398
    },         
      
    {
      Label: "Wisconsin Community Services (WCS)",
      Type: "Non-Profit",
      'Program and Services': [ "Assertive Community Treatment (ACT)"],
      Description: "\"The Community Support Program (CSP) - provides coordinated care and a range of treatment, rehabilitation and support services for individuals living in the community with severe and persistent mental illness with possible challenges related to abusing alcohol and other drugs. CSP provides services utilizing the evidence-based practice, Assertive Community Treatment (ACT) and Tools for Measurement of Assertive Community treatment (TMACT). Using the ACT model, a multidisciplinary intensive team-based approach provides participants services that are long-term, but with the ability to transition. These services include stage-wise interventions based on the participant’s wants and needs, including individual and group therapy along with other interventions to promote health. These services include: \n• Advocacy\n• Assessment\n• Benefit assistance\n• Psychiatry\n• Nursing\n• Case management/care coordination\n• Supportive groups\n• Medication assistance\n• Money management\n• On-site Pharmacy\n• Social support network\n\nTo be eligible for participation in the Assertive Community Treatment program, a consumer must:\n\n• Be 18 or older\n• Have a severe mental illness such as schizophrenia, bi-polar disorder or major depression\n• Have experienced difficulties in the last six months with housing, employment, medication management, legal issues, money management, or a worsening of symptoms that required emergency intervention or hospitalization\"",
      Tags: [ "Behavioral Health & Mental Health" ],
      Address: "3734 West Wisconsin Avenue\nMilwaukee, WI 53208",
      Phone: "(414) 344-6111",
      Fax: "(414) 344-2191",
      Email: "",
      Website: "www.wcs.org",
      Attributions: "",
      id: 2,
      lat: 43.038818,
      long: -87.960682
    },
    {
      "Label": "MICAH",
      "Type": "Non-Profit",
      "Program and Services": [ "MICAH'S ROC Wisconsin Taskforce"],
      "Description": "Restoring our Communities beyond 11 x 15 (ROC Wisconsin) is a statewide campaign of WISDOM. It began in 2011 as “11 X 15 For Safer, Healthier Communities” with a goal of reducing Wisconsin’s prison population by half — to 11,000 — by the end 2015. During those four years, we advocated for prison reform through health impact studies, Power Point presentations, actions, events, and media coverage.\n\nIn 2016 we renamed our campaign “ROC Wisconsin: Restoring our Communities beyond 11×15.” Our goals are to:\n\n- Restore communities that have been harmed by mass incarceration;\n- Restore families to wholeness and health;\n- Restore balance, fiscal discipline and humane priorities to our state’s criminal justice system;\n- Restore people to health through increased treatment alternatives to incarceration, decreased use of solitary confinement, and better support for those who return from jail or prison;\n- Restore men and women back to the community who do not need to be\n\nDuring 2017-2018, MICAH will be highlighting the issue of Crimeless Revocation. Presently people on probation, parole, or extended supervision can be revoked and re-incarcerated for violating rules of supervision even though they have not committed new offenses.\n\nA health impact assessment entitled “Excessive Revocations in Wisconsin” shows that Wisconsin incarcerated 3,000 individuals for crimeless revocations in 2015 alone. Thousands of others, who were never revoked, were held in county jails and state detention facilities while the Department of Corrections considered alleged rule violations.\n\nStatewide, MICAH with ROC Wisconsin is working:\n\nTo expand funds for Treatment Alternative and Diversion (TAD). TAD funds drug treatment courts, family courts, mental health courts and other interventions–which have proven more effective than incarceration in reducing recidivism. Evaluation of TAD-funded programs shows they save taxpayers $2 for every $1 the state has invested.\nTo pass the Second Chance This bipartisan legislation wouldreturn most 17-year-olds to the juvenile justice system. Concerns about the fiscal impact of the measure have been delaying passage.\nTo reduce and/or eliminate solitary confinement — now called segregation, administrative confinement, or restrictive Eliminate such isolation for mentally-ill prisoners and juveniles. End use of long-term confinement and document the number of days inmates spend in all levels of segregation.\nTo realize parole release for those eligible who can be released safely, and compassionate release for elderly and/or very ill prisoners who are no longer a danger to society.\nJoin us on the second Wednesday of every month at 5 pm for our task force meeting at the Project Return conference room, Welford Sanders Enterprise Center, 2821 N 4th St Suite 221, Milwaukee",
      "Tags": [ "Health", "Behavioral Health" ],
      "Address": "2625 N. WEIL STREET \nMILWAUKEE, WI 53212 \n",
      "Phone": "414.962.1200",
      "Fax": "414.962.2305",
      "Email": "",
      "Website": "https://www.metahouse.org/",
      "Attributions": "",
      id: 3,
      lat: 43.065959,
      long: -87.899192
    },
    {
      "Label": "Milwaukee County Department of Health and Services",
      "Type": "Govt. Org.",
      "Program and Services": [ "Milwaukee County Housing First"],
      "Description": "We provide housing...first.\n\nThe Housing First philosophy provides housing to those most in need without pre-condition. This is because, we have found, the most vulnerable in our community can only solve one life-changing problem at a time. When you are living outside, without a roof over your head or knowing where your next meal will come from, that instantly becomes your most important problem.\n\nDemanding the chronically homeless demonstrate sobriety, a clean bill of mental health, employment or anything else is, from what we have seen, putting the cart before the horse.\n\nHowever, when you remove that housing problem, suddenly the next problem facing that individual becomes \"most important,\" whether it be starting the road to recovery from undiagnosed mental health problems or substance abuse.\n\nMoreover, Milwaukee County Housing First saves a lot of money.\n\nTo Learn More\nhttps://www.youtube.com/watch?time_continue=3&v=pwdq2VWavtc&feature=emb_logo",
      "Tags": [ "Housing" ],
      "Address": "",
      "Phone": "",
      "Fax": "",
      "Email": "",
      "Website": "https://county.milwaukee.gov/EN/DHHS/Housing/Housing-First",
      "Attributions": "",
      id: 4,
      lat: 43.0,
      long: -87.0
    },
    {
      "Label": "Sojourner Family Peace Center",
      "Type": "Non-Profit",
      "Program and Services": ["Violence in the Workplace"],
      "Description": "Employers play an important role in making the workplace safe for victims of domestic violence. A safe work environment includes clear human resource policies, manager training, security, flexible leave and benefit policies and employee education.\nSFPC can help employers with training, policies and provide on-site advocacy if needed. Contact us to discuss how we can partner with you to make your workplace safe for victims of domestic violence to come forward.",
      "Tags": [ "Employment", "Behavioral Health & Mental Health"],
      "Address": "619 W. WALNUT ST, \nMILWAUKEE, WISCONSIN 53212",
      "Phone": "414-276-1911",
      "Fax": "414-727-2342",
      "Email": "",
      "Website": "https://familypeacecenter.org/resources/batterers-intervention-group/",
      "Attributions": "",
      id: 5,
      lat: 43.05248,
      long: -87.919407
    },
    {
      "Label": "UMOS",
      "Type": "Non-Profit",
      "Program and Services": ["Tech Hire"],
      "Description": "Focused on Wisconsin Residents\nHigher levels of skills will be needed to enter the ever emerging and expanding technostaff provided job placement assistance and accelerated technology-based skills training in web development, AutoCAD, HelpDesk and Microsoft Office Suite. Over 100 participants have enrolled.\n\nFocused on Employers\nUMOS TechHire staff develop customized training services to assist in meeting employer demand for a technology skilled workforce. TechHire staff provide a higher level of previously provided workforce development programing to meet the higher skill levels needed by employers.\n\nPilot Program\nUMOS partners with local companies to develop customized training for potential employee prospects with specific needed skills. For example, based on current data, a pilot training module for Computer Numerically Controlled Operators is being explored with a Milwaukee County Corrections Facility to meet the needs of area employers. Starting salaries for ex-offenders that complete the accelerated program before reentering their community could range from $30,000 to $55,000 per year.\n\nEastern Wisconsin TechHire Collaborative\nThe UMOS Eastern Wisconsin TechHire Collaborative, a partnership between UMOS, the College of Menominee Nation, and several employers, is designed to meet the overall workforce demand in technoTechHire program targets ages 17-29, with blended accelerated training, hands-on experience in web and software application development, real-world employer projects, and certification toward industry-recognized credentialing, such as Microsoft certifications.\n\nIndividualized Training Techniques\nUMOS offers various individualized training techniques for maximum participant learning:\n\nVirtual training from any location with an internet connection\nRemote instructional and coaching support\nWeb conferencing\nFace-to-face facilitated training workgroup sessions in the UMOS Technology Center in Milwaukee, Wisconsin\nClassroom instructor-led sessions through collaboration with the College of Menominee Nation in Keshena and Green Bay, Wisconsin.",
      "Tags":  [ "Employment" ],
      "Address": "2701 S. Chase Avenue \nMilwaukee, WI. 53207",
      "Phone": "",
      "Fax": "",
      "Email": "",
      "Website": "https://www.umos.org/",
      "Attributions": "",
      id: 6,
      lat: 42.994150,
      long: -87.912770
    },
    {
      "Label": "Pathfinders",
      "Type": "Non-Profit",
      "Program and Services": ["Positive Youth Development"],
      "Description": "At Pathfinders, we are committed to enabling a ladder of opportunity for young people. We value youth as vital assets to both our organization and community. We consider them to be partners and decision-makers in the services they receive, honoring their voices.",
      "Tags":  [ "Youth" ],
      "Address": "Pathfinders Main Office\n4200 N Holton St. Suite 400\nMilwaukee, WI 53212\n\nPathfinders Southeastern Education Center\n4200 N Holton St. Suite 400\nMilwaukee, WI 53212\n\nPathfinders Youth Shelter\n1614 E Kane Pl.\nMilwaukee, WI 53202",
      "Phone": "Pathfinders Main Office\n(414)964-2565\n\nPathfinders Southeastern Education Center\n(414)875-9452\n\nPathfinders Youth Shelter\n(414)271-1560",
      "Fax": "Pathfinders Main Office\n(414)964-0102\n\nPathfinders Southeastern Education Center\n(414)875-9004\n\nPathfinders Youth Shelter\n(414)271-1831",
      "Email": "info@pathfindersmke.org",
      "Website": "https://www.pathfindersmke.org/",
      "Attributions": "",
      id: 7,
      lat: 43.055760,
      long: -87.890620
    },
    {
      "Label": "Project Return",
      "Type": "Non-Profit",
      "Program and Services": ["Housing"],
      "Description": "A major issue facing individuals returning from incarceration is housing. Too many people return home only to find they don’t know where that is. Project RETURN works with landlords to open up housing opportunities to our clients who are in need.\n\nOffice Hours\n8:30am to 5:00pm\nMonday to Friday",
      "Tags":  [ "Housing" ],
      "Address": "2821 Vel R Phillips Ave, Suite 223 Milwaukee, WI 53212",
      "Phone": "(414) 374-8029",
      "Fax": "(414) 374-8033",
      "Email": "",
      "Website": "https://www.projectreturnmilwaukee.org/",
      "Attributions": "",
      id: 8,
      lat: 43.069901,
      long: -87.916199
    },
    {
      "Label": "Word of Hope",
      "Type": "Non-Profit",
      "Program and Services": ["]Mentoring Matters"],
      "Description": "Word of Hope has a strong mentoring component that will maintain regular contact with program participants, to assist with program retention. The mentoring program sessions are aimed to encourage positive thinking and behavior through self-examination, accountability and role modeling. mentors will support participants in maintaining a career path, family reunification and social skill development. the mentoring sessions are curriculum based and primarily focus on the 7 key areas in one’s life: Family, Community, Health, Personal Development, Financial, Social and Professional. Participants will identify with change and reduction of the recidivism rate.",
      "Tags":  [ "Employment", "Mental Health", "Health" ],
      "Address": "22677 N. 40th Street \nMilwaukee, WI 53210",
      "Phone": "414-447-1967",
      "Fax": "",
      "Email": "",
      "Website": "https://wordofhopeministriesinc.org/",
      "Attributions": "",
      id: 9,
      lat: 43.069720,
      long: -87.963330
    }
  ]
};
