export default {
  cognito: {
    REGION: WDP_AWS_REGION,
    USER_POOL_ID: WDP_AWS_USER_POOL_ID,
    APP_CLIENT_ID: WDP_AWS_APP_CLIENT_ID,
    IDENTITY_POOL_ID: WDP_AWS_IDENTITY_POOL_ID
  },
  api: {
    GRAPHQL_ENDPOINT: WDP_GRAPHQL_ENDPOINT
  }
};