name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! Thank you for your help in solving mass incarceration problems!'' first issue'
        pr-message: 'Your first PR, fantastic! Contributors will review it soon (~0-2 business days)!'' first pr'
